config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :time_slots
  resources :appointments
  resources :departments
  resources :hospitals, only: [:show, :index]
  devise_for :users
  devise_scope :user do
  resources :users, only: [:show, :index, :update, :create,:new]
    get '/users/sign_out' => 'devise/sessions#destroy'
    
  end
  root to: "dashboards#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/time_slot.rb
class TimeSlot < ApplicationRecord
end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  before_action :set_time_slot, only: %i[ show edit update destroy ]

  # GET /time_slots or /time_slots.json
  def index
    @time_slots = TimeSlot.all
  end

  # GET /time_slots/1 or /time_slots/1.json
  def show
  end

  # GET /time_slots/new
  def new
    @time_slot = TimeSlot.new
  end

  # GET /time_slots/1/edit
  def edit
  end

  # POST /time_slots or /time_slots.json
  def create
    @time_slot = TimeSlot.new(time_slot_params)

    respond_to do |format|
      if @time_slot.save
        format.html { redirect_to time_slot_url(@time_slot), notice: "Time slot was successfully created." }
        format.json { render :show, status: :created, location: @time_slot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_slots/1 or /time_slots/1.json
  def update
    respond_to do |format|
      if @time_slot.update(time_slot_params)
        format.html { redirect_to time_slot_url(@time_slot), notice: "Time slot was successfully updated." }
        format.json { render :show, status: :ok, location: @time_slot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_slots/1 or /time_slots/1.json
  def destroy
    @time_slot.destroy

    respond_to do |format|
      format.html { redirect_to time_slots_url, notice: "Time slot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_slot
      @time_slot = TimeSlot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def time_slot_params
      params.require(:time_slot).permit(:start_at, :end_at)
    end
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/time_slots/_form.html.erb
<%= form_with(model: time_slot) do |form| %>
  <% if time_slot.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(time_slot.errors.count, "error") %> prohibited this time_slot from being saved:</h2>

      <ul>
        <% time_slot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :start_at, style: "display: block" %>
    <%= form.datetime_field :start_at %>
  </div>

  <div>
    <%= form.label :end_at, style: "display: block" %>
    <%= form.datetime_field :end_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/time_slots/_time_slot.html.erb
<div id="<%= dom_id time_slot %>">
  <p>
    <strong>Start at:</strong>
    <%= time_slot.start_at %>
  </p>

  <p>
    <strong>End at:</strong>
    <%= time_slot.end_at %>
  </p>

</div>

app/views/time_slots/edit.html.erb
<h1>Editing time slot</h1>

<%= render "form", time_slot: @time_slot %>

<br>

<div>
  <%= link_to "Show this time slot", @time_slot %> |
  <%= link_to "Back to time slots", time_slots_path %>
</div>

app/views/time_slots/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Time slots</h1>

<div id="time_slots">
  <% @time_slots.each do |time_slot| %>
    <%= render time_slot %>
    <p>
      <%= link_to "Show this time slot", time_slot %>
    </p>
  <% end %>
</div>

<%= link_to "New time slot", new_time_slot_path %>

app/views/time_slots/new.html.erb
<h1>New time slot</h1>

<%= render "form", time_slot: @time_slot %>

<br>

<div>
  <%= link_to "Back to time slots", time_slots_path %>
</div>

app/views/time_slots/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @time_slot %>

<div>
  <%= link_to "Edit this time slot", edit_time_slot_path(@time_slot) %> |
  <%= link_to "Back to time slots", time_slots_path %>

  <%= button_to "Destroy this time slot", @time_slot, method: :delete %>
</div>