config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :time_slots
  resources :appointments
  resources :departments
  resources :hospitals, only: [:show, :index]
  devise_for :users
  devise_scope :user do
  resources :users, only: [:show, :index, :update, :create,:new]
    get '/users/sign_out' => 'devise/sessions#destroy'
    
  end
  root to: "dashboards#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :hospital
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    
  end

  # POST /users or /users.json
  def create
    @user = User.new(User_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "user was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "user was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "user was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email,:username,:designation,:active,:age,:gender,:hospital_id,:role,:name,:illeness_record,:feedback,:prescription,:amount_paid,:status)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    # def hospital_options
    #   @hospital = Hospital.all
    # end
end

app/views/users/_edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", patients_path %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



      <div class="form-group">
        <%= form.label :username %>
        <%= form.text_field :username, autofocus: true, autocomplete: 'username', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :email %>
        <%= form.email_field :email, autofocus: true, autocomplete: 'email', class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= form.label :age %>
        <%= form.number_field :age, autofocus: true, autocomplete: 'age', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :password %>
        <%= form.password_field :password, autocomplete: 'current-password', class: 'form-control' %>

        <% if @minimum_password_length %>
          <small class="form-text text-muted"><%= t('devise.shared.minimum_password_length', count: @minimum_password_length) %></small>
        <% end %>
      </div>

      <div class="form-group">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, autocomplete: 'current-password', class: 'form-control' %>
      </div>
      <div >
        <div class="field">    
          <%= form.label :gender %></br>
          <span class="option">Male<span><%= form.radio_button :gender, "M" %></br>
          <span class="option">Female<span><%= form.radio_button :gender, "F" %></br>
        </div>

        <div>
          <%= form.label :role %></br>
          <span class="option">Doctor<span><%= form.radio_button :role, "Doctor" %></br>
          <span class="option">Patient<span><%= form.radio_button :role, "Patient" %></br>
        </div>

   
          <%= form.label :designation %></br>
          <span class="option">Cardiologist<span><%= form.radio_button :designation, "Cardiologist" %></br>
          <span class="option">Neurologist<span><%= form.radio_button :designation, "Neurologist" %></br>
          <span class="option">General<span><%= form.radio_button :designation, "General" %></br>


          <%= form.label :hospital %><br>
          <%= form.collection_select :hospital_id, Hospital.all, :id, :name %>
        </div>
  
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :illness_record, style: "display: block" %>
    <%= form.text_area :illness_record %>
  </div>

  <div>
    <%= form.label :feedback, style: "display: block" %>
    <%= form.text_area :feedback %>
  </div>

  <div>
    <%= form.label :prescription, style: "display: block" %>
    <%= form.text_area :prescription %>
  </div>

  <div>
    <%= form.label :amount_paid, style: "display: block" %>
    <%= form.number_field :amount_paid %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_area :status %>
  </div>

  

  <div >
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p> 

  <p>
    <strong>User Name:</strong>
    <%= user.username %>
  </p> 

  <p>
    <strong>Designation:</strong>
    <%= user.designation %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= user.active %>
  </p>
  
  <p>
    <strong>Age:</strong>
    <%= user.age %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= user.gender %>
  </p>

  <p>
    <strong>Hospital_id:</strong>
    <%= user.hospital_id %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= user.role %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Illness record:</strong>
    <%= user.illness_record %>
  </p>

  <p>
    <strong>Feedback:</strong>
    <%= user.feedback %>
  </p>

  <p>
    <strong>Prescription:</strong>
    <%= user.prescription %>
  </p>

  <p>
    <strong>Amount paid:</strong>
    <%= user.amount_paid %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= user.status %>
  </p>

</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>users</h1>

<div id="users">
  <% @users.each do |user| %>
  
    <%= render user %>
    
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/users/user_doctors.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p> 

  <p>
    <strong>User Name:</strong>
    <%= user.username %>
  </p> 

  <p>
    <strong>Designation:</strong>
    <%= user.designation %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= user.active %>
  </p>
  
  <p>
    <strong>Age:</strong>
    <%= user.age %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= user.gender %>
  </p>

  <p>
    <strong>Hospital_id:</strong>
    <%= user.hospital_id %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= user.role %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Illness record:</strong>
    <%= user.illness_record %>
  </p>

  <p>
    <strong>Feedback:</strong>
    <%= user.feedback %>
  </p>

  <p>
    <strong>Prescription:</strong>
    <%= user.prescription %>
  </p>

  <p>
    <strong>Amount paid:</strong>
    <%= user.amount_paid %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= user.status %>
  </p>

</div>