config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :time_slots
  resources :appointments
  resources :departments
  resources :hospitals, only: [:show, :index]
  devise_for :users
  devise_scope :user do
  resources :users, only: [:show, :index, :update, :create,:new]
    get '/users/sign_out' => 'devise/sessions#destroy'
    
  end
  root to: "dashboards#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
    belongs_to :hospital
end

app/models/hospital.rb
class Hospital < ApplicationRecord
    has_many :users
end

app/models/patient.rb
class Patient < ApplicationRecord
    belongs_to :hospital
    has_many :hospital
end

app/models/time_slot.rb
class TimeSlot < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :hospital
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :gender, :designation, :age, :role, :hospital_id])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :gender, :designation, :age, :role, :hospital_id])
  end  
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    def index
    end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
    def index
        @hospitals = Hospital.all
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :illness_record, :feedback, :prescription, :amount_paid, :status)
    end
end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  before_action :set_time_slot, only: %i[ show edit update destroy ]

  # GET /time_slots or /time_slots.json
  def index
    @time_slots = TimeSlot.all
  end

  # GET /time_slots/1 or /time_slots/1.json
  def show
  end

  # GET /time_slots/new
  def new
    @time_slot = TimeSlot.new
  end

  # GET /time_slots/1/edit
  def edit
  end

  # POST /time_slots or /time_slots.json
  def create
    @time_slot = TimeSlot.new(time_slot_params)

    respond_to do |format|
      if @time_slot.save
        format.html { redirect_to time_slot_url(@time_slot), notice: "Time slot was successfully created." }
        format.json { render :show, status: :created, location: @time_slot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_slots/1 or /time_slots/1.json
  def update
    respond_to do |format|
      if @time_slot.update(time_slot_params)
        format.html { redirect_to time_slot_url(@time_slot), notice: "Time slot was successfully updated." }
        format.json { render :show, status: :ok, location: @time_slot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_slots/1 or /time_slots/1.json
  def destroy
    @time_slot.destroy

    respond_to do |format|
      format.html { redirect_to time_slots_url, notice: "Time slot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_slot
      @time_slot = TimeSlot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def time_slot_params
      params.require(:time_slot).permit(:start_at, :end_at)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    
  end

  # POST /users or /users.json
  def create
    @user = User.new(User_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "user was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "user was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "user was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email,:username,:designation,:active,:age,:gender,:hospital_id,:role,:name,:illeness_record,:feedback,:prescription,:amount_paid,:status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    # def hospital_options
    #   @hospital = Hospital.all
    # end
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-secondary text-white">
  <div class="container text-center">
    <small> &copy; <%= link_to " Github Link", "https://github.com/antimasingh070/Hospital-Management-System", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |role, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <%= link_to 'Hospital Management System', root_path, class: 'navbar-brand' %>
        <% if current_user %> 
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <%= link_to 'Hospital',hospitals_path,  class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Department', departments_path ,class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Appointments', appointments_path ,class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Users', users_path ,class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Profile', users_path ,class: 'nav-link' %>
                    </li>
                        <li class="nav-item">
                            <%= link_to 'Book Appointments', users_path ,class: 'nav-link' %>
                    </li>
                    

                </ul>
                <ul class='navbar-nav ml-auto'>
                    <li class='nav-item user-name'>
                        <%= current_user.name %>
                    </li>
                    <li class='nav-item'>
                        <%= link_to("Logout", destroy_user_session_path,
                            class: "btn btn-danger logout-button", method: :delete)%>
                    </li>
                </ul>
            </div>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelManagementSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    <div class="container">
      <%= render 'layouts/navigation' %>
        <div id="page-content">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>